version: 2.0

jobs:
  test:
    working_directory: ~/ratatouille
    docker: 
      - image: circleci/node:10
    steps:
      - checkout 
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint

  deploy:
    docker:
      - image: debian:8
    steps:
      - run:
          name: Install git
          command: |
            apt-get update
            apt-get install -y git
      - checkout 
      - add_ssh_keys
      - run:
          name: Add dokku to known_hosts
          command: ssh-keyscan -H deploy.somethingnew.co >> ~/.ssh/known_hosts
      - run:
          name: Deploy master to dokku
          command: |
            git remote add dokku dokku@deploy.somethingnew.co:ratatouille
            git push dokku master

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
